version: '3.8'

services:
  app:
    build:
      context: .
      target: runner
    tty: true
    stdin_open: true
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
